name: Validate

on:
  pull_request:
    paths:
      - 'default.json'
      - '.renovaterc.json5'
      - 'Makefile'
      - '.github/workflows/renovate-config-validate.yml'

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Run validation
        run: make validate
