name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5,7 * * *'

permissions:
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          private-key: ${{ secrets.RENOVATE_PRIVATE_KEY }}
          app-id: ${{ secrets.RENOVATE_APP_ID }}
          owner: ${{ github.repository_owner }}
          repositories: |
            .github
            cli
            docs
            go-billy
            go-git
            go-git-fixtures
            gcfg

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@22e0a16091fc706b04affe6ae53d5e3358ac4023 # v46.1.19
        with:
          configurationFile: default.json
          token: '${{ steps.get_token.outputs.token }}'
        env:
          LOG_LEVEL: debug
          RENOVATE_USERNAME: go-git-renovate[bot]
          RENOVATE_GIT_NAME: go-git-renovate[bot]
          RENOVATE_GIT_EMAIL: go-git-renovate[bot]@users.noreply.github.com
          RENOVATE_ONBOARDING: 'false'
          RENOVATE_REPOSITORIES: go-git/.github,go-git/cli,go-git/docs,go-git/go-billy,go-git/go-git,go-git/go-git-fixtures,go-git/gcfg
