name: Validate

on:
  pull_request:
    paths:
      - 'default.json'
      - '.renovaterc.json5'
      - 'Makefile'
      - '.github/workflows/renovate-config-validate.yml'

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Run validation
        run: make validate
